function setTab(tab){activeTab=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==`view-${tab}`));renderAll()}
function renderAll(){if(!$('appView')||$('appView').classList.contains('hidden'))return;renderDashboard();renderForecastTable();renderSettings();renderAccuracy()}

function renderDashboard(){
 const today=todayISO(),current=rows.find(r=>r.forecast_date===today)||rows.find(r=>r.forecast_date>=today)||rows.at(-1);if(!current)return;
 const next14=rows.filter(r=>r.forecast_date>=today).slice(0,14),month=monthKey(current.forecast_date),monthRows=rows.filter(r=>monthKey(r.forecast_date)===month),actualDone=rows.filter(r=>Number(r.actual_total)>0&&rowErrorRate(r)!=null),recent=actualDone.slice(-30);const mae=recent.length?recent.reduce((z,r)=>z+Math.abs(rowError(r)),0)/recent.length:0,mape=recent.length?recent.reduce((z,r)=>z+rowErrorRate(r),0)/recent.length:0;
 $('kpiToday').textContent=fmtInt(current.final_forecast)+'件';$('kpiPeople').textContent=fmtInt(current.required_people)+'人';$('kpiEvent').textContent=current.event_type||'通常';$('kpiMonth').textContent=fmtInt(monthRows.reduce((z,r)=>z+Number(r.actual_total||r.final_forecast||0),0))+'件';$('kpiAccuracy').textContent=recent.length?(100-mape*100).toFixed(1)+'%':'—';$('kpiMae').textContent=recent.length?`平均誤差 ${fmtInt(mae)}件`:'実績蓄積後に表示';
 $('todayDetail').innerHTML=`<div><span>前年実績</span><b>${fmtInt(current.prior_year_actual)}件</b></div><div><span>システム予測</span><b>${fmtInt(current.system_forecast)}件</b></div><div><span>手動補正</span><b>${current.manual_adjustment>=0?'+':''}${fmtInt(current.manual_adjustment)}件</b></div><div><span>配送予測</span><b>佐川 ${fmtInt(current.forecast_sagawa)} / ネコ ${fmtInt(current.forecast_nekopos)} / ゆう ${fmtInt(current.forecast_yupack)}</b></div>`;
 renderMiniChart(next14)
}
function renderMiniChart(data){const box=$('forecastChart');if(!data.length){box.innerHTML='';return}const max=Math.max(...data.map(r=>Number(r.final_forecast||0)),1);box.innerHTML=data.map(r=>{const h=Math.max(4,Math.round(Number(r.final_forecast||0)/max*150));const cls=r.event_type==='通常'?'':'event';return `<div class="barcol"><div class="barvalue">${fmtInt(r.final_forecast)}</div><div class="bar ${cls}" style="height:${h}px" title="${esc(r.event_type)}"></div><div class="barlabel">${ymdLabel(r.forecast_date)}<br><small>${esc(r.weekday)}</small></div></div>`}).join('')}

function renderForecastTable(){
 const month=$('monthFilter').value||'',state=$('stateFilter').value||'all';let list=rows;if(month)list=list.filter(r=>monthKey(r.forecast_date)===month);if(state==='actual')list=list.filter(r=>Number(r.actual_total)>0);if(state==='forecast')list=list.filter(r=>!Number(r.actual_total)>0);
 const tb=$('forecastBody');tb.innerHTML='';for(const r of list){const err=rowError(r),diffStaff=r.actual_staff==null?null:Number(r.actual_staff)-Number(r.required_people);const tr=document.createElement('tr');if(r.forecast_date===todayISO())tr.classList.add('today-row');tr.innerHTML=`<td><button class="linkdate" data-open="${r.forecast_date}">${ymdLabel(r.forecast_date)}</button></td><td>${esc(r.weekday)}</td><td><span class="badge ${r.event_type==='通常'?'':'event'}">${esc(r.event_type)}</span></td><td class="num">${fmtInt(r.prior_year_actual)}</td><td class="num">${fmtInt(r.final_forecast)}</td><td class="num">${r.actual_total==null?'—':fmtInt(r.actual_total)}</td><td class="num ${err==null?'':Math.abs(err)<=100?'oktext':'warntext'}">${err==null?'—':(err>0?'+':'')+fmtInt(err)}</td><td class="num">${fmtInt(r.required_people)}</td><td class="num">${r.actual_staff==null?'—':fmt1(r.actual_staff)}</td><td class="num">${diffStaff==null?'—':(diffStaff>=0?'+':'')+fmt1(diffStaff)}</td><td>${r.completed_at?String(r.completed_at).slice(0,5):'—'}</td>`;tb.appendChild(tr)}
 tb.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDay(b.dataset.open));$('rowCount').textContent=`${list.length}日`;
}

function openDay(dateStr){const r=rows.find(x=>x.forecast_date===dateStr);if(!r)return;$('dayDate').value=r.forecast_date;$('dayTitle').textContent=`${r.forecast_date}（${r.weekday}） ${r.event_type}`;$('dPrior').textContent=fmtInt(r.prior_year_actual)+'件';$('dSystem').textContent=fmtInt(r.system_forecast)+'件';$('dFinal').textContent=fmtInt(r.final_forecast)+'件';$('dRequired').textContent=fmtInt(r.required_people)+'人';$('dManual').value=r.manual_adjustment||0;$('dActual').value=r.actual_total??'';$('dSagawa').value=r.actual_sagawa??'';$('dNekopos').value=r.actual_nekopos??'';$('dYupack').value=r.actual_yupack??'';$('dStaff').value=r.actual_staff??'';$('dTemp').value=r.temp_staff??'';$('dCompleted').value=r.completed_at?String(r.completed_at).slice(0,5):'';$('dNote').value=r.note||'';updateDaySum();$('dayDlg').showModal()}
function updateDaySum(){const total=Number($('dActual').value||0),sum=['dSagawa','dNekopos','dYupack'].reduce((z,id)=>z+Number($(id).value||0),0);$('deliverySum').textContent=`配送合計 ${fmtInt(sum)}件 / 総数 ${fmtInt(total)}件`;$('deliverySum').className=sum===total&&total>0?'sumcheck ok':'sumcheck '+(sum||total?'ng':'')}
async function submitDay(e){e.preventDefault();const b=$('saveDayBtn');b.disabled=true;b.textContent='保存中…';try{await saveActual({forecast_date:$('dayDate').value,actual_total:$('dActual').value,actual_sagawa:$('dSagawa').value,actual_nekopos:$('dNekopos').value,actual_yupack:$('dYupack').value,actual_staff:$('dStaff').value,temp_staff:$('dTemp').value,completed_at:$('dCompleted').value,note:$('dNote').value});$('dayDlg').close();toast('実績を保存し、未来予測を再計算しました。')}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='実績を保存'} }
async function submitManual(){try{await saveManualForecast($('dayDate').value,$('dManual').value);const r=rows.find(x=>x.forecast_date===$('dayDate').value);$('dFinal').textContent=fmtInt(r.final_forecast)+'件';$('dRequired').textContent=fmtInt(r.required_people)+'人';toast('手動補正を保存しました。')}catch(e){alert(e.message)}}

function renderSettings(){
 $('prodInput').value=getRule('productivity','shipments_per_person',180);const wg=$('weekdayRules');wg.innerHTML=['月','火','水','木','金','土','日'].map(w=>{const r=rules.find(x=>x.rule_group==='weekday_growth'&&x.rule_key===w);return `<tr><td>${w}</td><td class="num">${r?Number(r.rule_value).toFixed(3):'—'}</td><td class="num">${r?.sample_count||0}日</td></tr>`}).join('');
 const er=$('eventRules');const e=rules.filter(x=>x.rule_group==='event_multiplier');er.innerHTML=e.map(r=>`<tr><td>${esc(r.rule_key)}</td><td class="num">${Number(r.rule_value).toFixed(3)}</td><td class="num">${r.sample_count||0}日</td></tr>`).join('');
 const s=getRule('carrier_share','sagawa',0),n=getRule('carrier_share','nekopos',0),y=getRule('carrier_share','yupack',0);$('carrierRules').innerHTML=`<div><span>佐川</span><b>${pct(s)}</b></div><div><span>ネコポス</span><b>${pct(n)}</b></div><div><span>ゆうパック</span><b>${pct(y)}</b></div>`;$('sourcePeriod').textContent=`実績期間 2026/2/21 ～ ${latestActualDate()}`
}

function renderAccuracy(){
 const done=rows.filter(r=>Number(r.actual_total)>0&&rowErrorRate(r)!=null),recent=done.slice(-60);const byWd={};for(const wd of ['月','火','水','木','金','土','日']){const s=recent.filter(r=>r.weekday===wd);byWd[wd]=s.length?{n:s.length,bias:s.reduce((z,r)=>z+rowError(r),0)/s.length,mape:s.reduce((z,r)=>z+rowErrorRate(r),0)/s.length}:null}
 $('accuracyBody').innerHTML=Object.entries(byWd).map(([wd,v])=>`<tr><td>${wd}</td><td class="num">${v?.n||0}</td><td class="num">${v?(v.bias>0?'+':'')+fmtInt(v.bias):'—'}</td><td class="num">${v?p(v.mape):'—'}</td></tr>`).join('');
 function p(v){return (v*100).toFixed(1)+'%'}
}

function toast(msg){const x=$('toast');x.textContent=msg;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}

$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('monthFilter').onchange=renderForecastTable;$('stateFilter').onchange=renderForecastTable;$('dayForm').onsubmit=submitDay;$('dayCancel').onclick=()=>$('dayDlg').close();$('saveManualBtn').onclick=submitManual;['dActual','dSagawa','dNekopos','dYupack'].forEach(id=>$(id).oninput=updateDaySum);$('saveProdBtn').onclick=async()=>{try{await saveProductivity($('prodInput').value);toast('必要人数の換算値を更新しました。')}catch(e){alert(e.message)}};$('recalcBtn').onclick=async()=>{try{await persistRecalculation();renderAll();toast('実績から係数と未来予測を再計算しました。')}catch(e){alert(e.message)}};$('resetDemoBtn').onclick=()=>{if(confirm('ローカルプレビューの変更を初期状態に戻しますか？')){resetLocal();renderAll();toast('初期状態へ戻しました。')}};

(async function boot(){
 await (window.FORECAST365_READY||Promise.resolve());
 const months=[...new Set((window.FORECAST365_SEED||[]).map(r=>monthKey(r.forecast_date)))];$('monthFilter').innerHTML='<option value="">全期間</option>'+months.map(m=>`<option value="${m}">${m.replace('-','年')}月</option>`).join('');
 session=loadSession();if(session?.access_token){(async()=>{try{user=await req('/auth/v1/user');await initialize()}catch{saveSession(null);session=null;user=null;showAuth();loadLocal()}})()}else{showAuth();loadLocal()}
})();
