async function saveMonth(){
 const b=$('saveMonthBtn');b.disabled=true;b.textContent='保存中…';
 try{
  const m=monthDate(),plan={owner_id:user.id,plan_month:m,planned_shipments:Math.round(n($('shipments').value)),target_oplh:n($('targetOplh').value)||32,safety_buffer_pct:n($('bufferPct').value)};
  await rest('logistics_monthly_plans','on_conflict=owner_id%2Cplan_month',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(plan)});
  const now=new Date().toISOString(),rows=monthRows.map(r=>({owner_id:user.id,staff_id:r.staff_id,plan_month:m,work_days:n(r.work_days),included:!!r.included,start_time:r.start_time||null,end_time:r.end_time||null,break_start:r.break_start||null,break_end:r.break_end||null,updated_at:now}));
  if(rows.length)await rest('logistics_monthly_staffing','on_conflict=owner_id%2Cstaff_id%2Cplan_month',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(rows)});
  dirty=false;updateDirty();await loadMonth()
 }catch(e){alert('保存に失敗しました: '+e.message)}finally{b.disabled=false;b.textContent='変更を保存'}
}
async function copyPrevious(){const cur=monthDate();try{const rows=await rest('logistics_monthly_staffing',`owner_id=eq.${user.id}&plan_month=lt.${cur}&select=*&order=plan_month.desc`);if(!rows?.length){alert('前月以前の設定がありません。');return}const latest=rows[0].plan_month,src=rows.filter(x=>x.plan_month===latest);monthRows.forEach(r=>{const p=src.find(x=>x.staff_id===r.staff_id);if(p){r.work_days=p.work_days;r.included=p.included;r.start_time=p.start_time||r.default?.start_time||r.start_time;r.end_time=p.end_time||r.default?.end_time||r.end_time;r.break_start=p.break_start;r.break_end=p.break_end}});markDirty();renderMonthly()}catch(e){alert(e.message)}}
function resetDefaults(){monthRows.forEach(r=>{const d=r.default;if(d){r.work_days=d.default_work_days;r.included=true;r.start_time=d.start_time;r.end_time=d.end_time;r.break_start=d.break_start;r.break_end=d.break_end}else{r.work_days=0;r.included=false}});markDirty();renderMonthly()}
function renderMaster(){
 const tb=$('masterBody');tb.innerHTML='';
 const sorted=staff.map(s=>{const d=defaults.find(x=>x.staff_id===s.id),c=calcSchedule({start_time:d?.start_time,end_time:d?.end_time,break_start:d?.break_start,break_end:d?.break_end,work_days:1});return{s,d,c}}).sort((a,b)=>{const av=masterSort.key==='name'?String(a.s.name||''):masterSort.key==='type'?String(a.s.employment_type||''):masterSort.key==='shipDay'?a.c.shipDay:n(a.d?.default_work_days),bv=masterSort.key==='name'?String(b.s.name||''):masterSort.key==='type'?String(b.s.employment_type||''):masterSort.key==='shipDay'?b.c.shipDay:n(b.d?.default_work_days);const cmp=typeof av==='string'?av.localeCompare(bv,'ja',{numeric:true,sensitivity:'base'}):av-bv;return masterSort.dir==='asc'?cmp:-cmp});
 if(!sorted.length)tb.innerHTML='<tr><td colspan="8" class="small">従業員マスタがありません。</td></tr>';
 for(const {s,d,c} of sorted){const hasSchedule=!!(d?.start_time&&d?.end_time),tr=document.createElement('tr');tr.innerHTML=`<td><b>${esc(s.name)}</b></td><td>${esc(s.employment_type)}</td><td>${hasSchedule?String(d.start_time).slice(0,5)+'～'+String(d.end_time).slice(0,5):'—'}</td><td>${d?.break_start&&d?.break_end?String(d.break_start).slice(0,5)+'～'+String(d.break_end).slice(0,5):'なし'}</td><td class="num">${hasSchedule?fmt(c.shipDay,2)+'h':'—'}</td><td class="num">${d?fmt(n(d.default_work_days),1)+'日':'—'}</td><td>${esc(d?.notes||s.notes||'')}</td><td><button data-edit="${s.id}">編集</button></td>`;tb.appendChild(tr)}
 tb.querySelectorAll('[data-edit]').forEach(x=>x.onclick=()=>openStaff(x.dataset.edit));updateSortHeaders()
}
function updateSortHeaders(){document.querySelectorAll('[data-msort]').forEach(b=>{const active=b.dataset.msort===monthlySort.key;b.classList.toggle('active',active);b.querySelector('.sortMark').textContent=active?(monthlySort.dir==='asc'?'▲':'▼'):'↕'});document.querySelectorAll('[data-sort]').forEach(b=>{const active=b.dataset.sort===masterSort.key;b.classList.toggle('active',active);b.querySelector('.sortMark').textContent=active?(masterSort.dir==='asc'?'▲':'▼'):'↕'})}
function bindSortHeaders(){document.querySelectorAll('[data-msort]').forEach(b=>b.onclick=()=>{const k=b.dataset.msort;if(monthlySort.key===k)monthlySort.dir=monthlySort.dir==='asc'?'desc':'asc';else monthlySort={key:k,dir:'asc'};renderMonthly()});document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;if(masterSort.key===k)masterSort.dir=masterSort.dir==='asc'?'desc':'asc';else masterSort={key:k,dir:'asc'};renderMaster()});updateSortHeaders()}
function breakMode(bs,be){if(!bs||!be)return'none';return String(bs).slice(0,5)==='12:00'&&String(be).slice(0,5)==='13:00'?'one':'custom'}function toggleBreak(prefix){const c=$(prefix+'BreakMode').value==='custom';$(prefix+'BreakStartWrap').classList.toggle('hidden',!c);$(prefix+'BreakEndWrap').classList.toggle('hidden',!c)}function getBreak(prefix){const m=$(prefix+'BreakMode').value;if(m==='one')return['12:00','13:00'];if(m==='custom')return[$(prefix+'BreakStart').value,$(prefix+'BreakEnd').value];return[null,null]}
function openStaff(id=null){editingStaff=id;const s=id?staff.find(x=>x.id===id):null,d=id?defaults.find(x=>x.staff_id===id):null;$('staffDlgTitle').textContent=id?'従業員編集':'従業員追加';$('fName').value=s?.name||'';$('fType').value=s?.employment_type||'パート';$('fStart').value=String(d?.start_time||'09:00').slice(0,5);$('fEnd').value=String(d?.end_time||'16:00').slice(0,5);$('fDays').value=d?.default_work_days??16;$('fNotes').value=d?.notes||s?.notes||'';$('fBreakMode').value=breakMode(d?.break_start,d?.break_end);$('fBreakStart').value=String(d?.break_start||'12:00').slice(0,5);$('fBreakEnd').value=String(d?.break_end||'13:00').slice(0,5);toggleBreak('f');previewStaff();$('staffDlg').showModal()}
function previewStaff(){const [bs,be]=getBreak('f'),c=calcSchedule({start_time:$('fStart').value,end_time:$('fEnd').value,break_start:bs,break_end:be,work_days:n($('fDays').value)});$('fPreview').textContent=`出荷人時 ${fmt(c.shipDay,2)}h/日 × ${fmt(n($('fDays').value),1)}日 = ${fmt(c.shipMonth)}h/月`}
async function saveStaff(e){e.preventDefault();const name=$('fName').value.trim();if(!name)return;try{let id=editingStaff;if(id)await rest('logistics_staff',`id=eq.${id}`,{method:'PATCH',body:JSON.stringify({name,employment_type:$('fType').value,notes:$('fNotes').value})});else{const x=await rest('logistics_staff','select=*',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({owner_id:user.id,name,employment_type:$('fType').value,is_active:true,notes:$('fNotes').value})});id=x[0].id}const[bs,be]=getBreak('f'),body={staff_id:id,owner_id:user.id,start_time:$('fStart').value,end_time:$('fEnd').value,break_start:bs,break_end:be,default_work_days:n($('fDays').value),notes:$('fNotes').value,updated_at:new Date().toISOString()};await rest('logistics_staff_defaults','on_conflict=staff_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(body)});$('staffDlg').close();await loadAll()}catch(e){alert('保存に失敗しました: '+e.message)}}
function openMonthSchedule(i){editingMonthIndex=i;const r=monthRows[i];$('msName').textContent=r.staff.name;$('msStart').value=String(r.start_time).slice(0,5);$('msEnd').value=String(r.end_time).slice(0,5);$('msBreakMode').value=breakMode(r.break_start,r.break_end);$('msBreakStart').value=String(r.break_start||'12:00').slice(0,5);$('msBreakEnd').value=String(r.break_end||'13:00').slice(0,5);toggleBreak('ms');$('monthScheduleDlg').showModal()}
$('monthScheduleForm').onsubmit=e=>{e.preventDefault();const r=monthRows[editingMonthIndex],[bs,be]=getBreak('ms');r.start_time=$('msStart').value;r.end_time=$('msEnd').value;r.break_start=bs;r.break_end=be;markDirty();$('monthScheduleDlg').close();renderMonthly()};$('msReset').onclick=()=>{const r=monthRows[editingMonthIndex],d=r.default;if(d){r.start_time=d.start_time;r.end_time=d.end_time;r.break_start=d.break_start;r.break_end=d.break_end;markDirty();renderMonthly()}$('monthScheduleDlg').close()}
function selfTest(){const tests=[];const eq=(a,b)=>Math.abs(a-b)<1e-9;tests.push(eq(calcSchedule({start_time:'09:00',end_time:'16:00',break_start:'12:00',break_end:'13:00',work_days:18}).shipDay,5.5));tests.push(eq(calcSchedule({start_time:'09:00',end_time:'15:00',break_start:'12:00',break_end:'13:00',work_days:18}).shipDay,5));tests.push(eq(calcSchedule({start_time:'09:00',end_time:'13:00',break_start:null,break_end:null,work_days:18}).shipDay,4));tests.push(eq(calcSchedule({start_time:'10:45',end_time:'17:15',break_start:'12:00',break_end:'13:00',work_days:14}).shipDay,3.75));tests.push(eq(60000/32,1875));const ok=tests.every(Boolean);$('selfCheck').textContent=ok?'✓ 正常':'✕ 異常';$('selfCheck').className=ok?'okline':'ngline';return ok}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('monthlyTab').classList.toggle('hidden',b.dataset.tab!=='monthly');$('masterTab').classList.toggle('hidden',b.dataset.tab!=='master')});$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('month').onchange=async()=>{if(dirty&&!confirm('未保存の変更があります。月を切り替えますか？')){$('month').value=lastLoadedMonth;return}try{await loadMonth()}catch{if(lastLoadedMonth)$('month').value=lastLoadedMonth}};['shipments','targetOplh','bufferPct'].forEach(id=>$(id).oninput=()=>{markDirty();renderMonthly()});$('saveMonthBtn').onclick=saveMonth;$('copyPrevBtn').onclick=copyPrevious;$('resetDefaultBtn').onclick=resetDefaults;$('addStaffBtn').onclick=()=>openStaff();$('staffCancel').onclick=()=>$('staffDlg').close();$('staffForm').onsubmit=saveStaff;$('fBreakMode').onchange=()=>{toggleBreak('f');previewStaff()};['fStart','fEnd','fDays','fBreakStart','fBreakEnd'].forEach(id=>$(id).oninput=previewStaff);$('msBreakMode').onchange=()=>toggleBreak('ms');$('msCancel').onclick=()=>$('monthScheduleDlg').close();bindSortHeaders();
(async()=>{
 selfTest();session=loadSession();
 if(session?.access_token){
  try{user=await req('/auth/v1/user');showApp();try{await loadAll()}catch(e){showDataError(e)}}
  catch{saveSession(null);session=null;user=null;showApp()}
 }else showApp()
})();
