(function(){
  const state={month:'',planMonth:'',start:'',end:'',dates:[],staff:[],defaults:[],staffing:[],forecast:new Map(),shifts:new Map(),targetOplh:32,bufferPct:0,planSource:'default',loaded:false};
  const gid=id=>document.getElementById(id),num=v=>{const x=Number(v);return Number.isFinite(x)?x:0},key=(sid,d)=>sid+'|'+d,pad=v=>String(v).padStart(2,'0'),jpWeek=['日','月','火','水','木','金','土'];
  const holidayCache=new Map();
  function utcYmd(d){return d.getUTCFullYear()+'-'+pad(d.getUTCMonth()+1)+'-'+pad(d.getUTCDate())}
  function periodForMonth(ym){const[y,m]=String(ym).split('-').map(Number),start=new Date(Date.UTC(y,m-2,21)),end=new Date(Date.UTC(y,m-1,20)),dates=[];for(let d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1))dates.push(utcYmd(d));return{start:utcYmd(start),end:utcYmd(end),dates,planMonth:`${y}-${pad(m)}-01`}}
  function dateInfo(date){const d=new Date(date+'T00:00:00Z');return{md:(d.getUTCMonth()+1)+'/'+d.getUTCDate(),weekday:jpWeek[d.getUTCDay()],dow:d.getUTCDay(),weekend:d.getUTCDay()===0||d.getUTCDay()===6}}
  function addDays(s,n){const d=new Date(s+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return utcYmd(d)}
  function nthMonday(y,m,n){const d=new Date(Date.UTC(y,m-1,1)),first=1+((8-d.getUTCDay())%7);return `${y}-${pad(m)}-${pad(first+(n-1)*7)}`}
  function japanHolidays(y){
    if(holidayCache.has(y))return holidayCache.get(y);const s=new Set(),add=(m,d)=>s.add(`${y}-${pad(m)}-${pad(d)}`);
    add(1,1);s.add(nthMonday(y,1,2));add(2,11);if(y>=2020)add(2,23);
    add(3,Math.floor(20.8431+0.242194*(y-1980)-Math.floor((y-1980)/4)));add(4,29);add(5,3);add(5,4);add(5,5);
    s.add(nthMonday(y,7,3));add(8,11);s.add(nthMonday(y,9,3));add(9,Math.floor(23.2488+0.242194*(y-1980)-Math.floor((y-1980)/4)));s.add(nthMonday(y,10,2));add(11,3);add(11,23);
    const base=[...s].sort();for(const h of base){const d=new Date(h+'T00:00:00Z');if(d.getUTCDay()===0){let x=addDays(h,1);while(s.has(x))x=addDays(x,1);s.add(x)}}
    let changed=true;while(changed){changed=false;for(let d=new Date(Date.UTC(y,0,2));d<=new Date(Date.UTC(y,11,30));d.setUTCDate(d.getUTCDate()+1)){const x=utcYmd(d);if(s.has(x)||d.getUTCDay()===0)continue;if(s.has(addDays(x,-1))&&s.has(addDays(x,1))){s.add(x);changed=true}}}
    holidayCache.set(y,s);return s
  }
  function isJapaneseHoliday(date){return japanHolidays(Number(date.slice(0,4))).has(date)}
  function staffById(sid){return state.staff.find(x=>x.id===sid)}
  function afterRetirement(sid,date){const d=staffById(sid)?.retirement_date;return !!d&&date>String(d).slice(0,10)}
  function visibleInPeriod(s,start){return !s?.retirement_date||String(s.retirement_date).slice(0,10)>=start}
  function targetDays(sid){const r=state.staffing.find(x=>x.staff_id===sid);if(!r||!r.included||!r.start_time||!r.end_time)return 0;const base=Math.max(0,Math.round(num(r.work_days))),available=state.dates.filter(d=>!afterRetirement(sid,d)).length;return Math.min(base,available)}
  function shipHoursDay(sid){const r=state.staffing.find(x=>x.staff_id===sid);return !r||!r.included?0:calcSchedule({...r,work_days:1}).shipDay}
  function requiredPeople(d){return Math.max(0,Math.round(num(state.forecast.get(d)?.required_people)))}
  function requiredHours(d){const f=state.forecast.get(d);return !f||state.targetOplh<=0?0:num(f.final_forecast)/state.targetOplh*(1+state.bufferPct/100)}
  function getCell(sid,date){const k=key(sid,date);let c=state.shifts.get(k);if(!c){c={owner_id:user.id,staff_id:sid,plan_month:state.planMonth,shift_date:date,assignment:'off',lock_type:'auto',exists:false};state.shifts.set(k,c)}return c}
  function isWork(sid,d){return !afterRetirement(sid,d)&&getCell(sid,d).assignment==='work'}
  function assignedCount(d){let c=0;for(const s of state.staff)if(isWork(s.id,d))c++;return c}
  function assignedHours(d){let h=0;for(const s of state.staff)if(isWork(s.id,d))h+=shipHoursDay(s.id);return h}
  function assignedForStaff(sid){let c=0;for(const d of state.dates)if(isWork(sid,d))c++;return c}
  function weekendForStaff(sid){let c=0;for(const d of state.dates)if(dateInfo(d).weekend&&isWork(sid,d))c++;return c}
  function projectedStreak(sid,date){const i=state.dates.indexOf(date);if(i<0)return 1;let l=0,r=0;for(let x=i-1;x>=0&&isWork(sid,state.dates[x]);x--)l++;for(let x=i+1;x<state.dates.length&&isWork(sid,state.dates[x]);x++)r++;return l+1+r}
  function maxConsecutive(){let m=0;for(const s of state.staff){let c=0;for(const d of state.dates){if(isWork(s.id,d)){c++;m=Math.max(m,c)}else c=0}}return m}
  function stableTie(sid,date){let h=0;for(const ch of sid+date)h=(h*31+ch.charCodeAt(0))%997;return h/997}
  function rule(sid){return state.defaults.find(x=>x.staff_id===sid)||{}}
  function dayAllowed(sid,date){if(afterRetirement(sid,date))return false;const r=rule(sid),inf=dateInfo(date);if(r.no_weekends_holidays&&(inf.weekend||isJapaneseHoliday(date)))return false;if(r.no_sundays&&inf.dow===0)return false;return true}
  function autoAllowed(sid,date){if(!dayAllowed(sid,date))return false;const r=rule(sid);if(r.no_four_consecutive&&projectedStreak(sid,date)>=4)return false;return true}

  function constraintText(d){const a=[];if(d?.no_weekends_holidays)a.push('土日祝不可');else if(d?.no_sundays)a.push('日曜不可');if(d?.no_four_consecutive)a.push('4連勤不可');return a.length?a.join('・'):'なし'}
  function ensureMasterConstraintUI(){
    const form=gid('staffForm'),grid=form?.querySelector('.mgrid');if(grid&&!gid('fNoWeekendsHolidays')){const w=document.createElement('div');w.className='wide';w.innerHTML='<label>シフト勤務条件</label><div class="toolbar"><label style="display:flex;align-items:center;gap:6px;margin:0"><input class="check" id="fNoWeekendsHolidays" type="checkbox">土日祝不可</label><label style="display:flex;align-items:center;gap:6px;margin:0"><input class="check" id="fNoSundays" type="checkbox">日曜のみ不可</label><label style="display:flex;align-items:center;gap:6px;margin:0"><input class="check" id="fNoFourConsecutive" type="checkbox">4連勤不可</label></div>';grid.insertBefore(w,gid('fPreview'));gid('fNoWeekendsHolidays').onchange=syncConstraintChecks}
    const table=gid('masterTable'),hr=table?.querySelector('thead tr');if(hr&&!hr.querySelector('[data-constraint-head]')){const th=document.createElement('th');th.dataset.constraintHead='1';th.textContent='勤務条件';hr.insertBefore(th,hr.children[6]);const cg=table.querySelector('colgroup');if(cg){const col=document.createElement('col');col.style.width='230px';cg.insertBefore(col,cg.children[6])}}
  }
  function syncConstraintChecks(){const all=gid('fNoWeekendsHolidays'),sun=gid('fNoSundays');if(!all||!sun)return;if(all.checked){sun.checked=false;sun.disabled=true}else sun.disabled=false}
  function decorateMasterRows(){ensureMasterConstraintUI();const tb=gid('masterBody');if(!tb)return;for(const tr of tb.querySelectorAll('tr')){const edit=tr.querySelector('[data-edit]');if(!edit){const td=tr.querySelector('td[colspan]');if(td)td.colSpan=10;continue}const d=defaults.find(x=>x.staff_id===edit.dataset.edit),td=document.createElement('td');td.className='staff-constraint-cell small';td.textContent=constraintText(d);tr.insertBefore(td,tr.children[6])}}
  function installMasterConstraintHooks(){
    ensureMasterConstraintUI();const oldRender=window.renderMaster,oldOpen=window.openStaff,oldSave=window.saveStaff;
    window.renderMaster=function(){oldRender();decorateMasterRows()};
    window.openStaff=function(id=null){ensureMasterConstraintUI();oldOpen(id);const d=id?defaults.find(x=>x.staff_id===id):null;gid('fNoWeekendsHolidays').checked=!!d?.no_weekends_holidays;gid('fNoSundays').checked=!!d?.no_sundays;gid('fNoFourConsecutive').checked=!!d?.no_four_consecutive;syncConstraintChecks()};
    window.saveStaff=async function(e){const was=editingStaff,name=gid('fName').value.trim(),vals={no_weekends_holidays:!!gid('fNoWeekendsHolidays')?.checked,no_sundays:!!gid('fNoSundays')?.checked,no_four_consecutive:!!gid('fNoFourConsecutive')?.checked};await oldSave(e);if(gid('staffDlg')?.open)return;let id=was;if(!id){const q=await rest('logistics_staff',`owner_id=eq.${user.id}&name=eq.${encodeURIComponent(name)}&select=id,created_at&order=created_at.desc&limit=1`);id=q?.[0]?.id}if(id){await rest('logistics_staff_defaults',`staff_id=eq.${id}`,{method:'PATCH',body:JSON.stringify({...vals,updated_at:new Date().toISOString()})});await loadAll()}};
    gid('staffForm').onsubmit=window.saveStaff;gid('addStaffBtn').onclick=()=>window.openStaff();
    if(user?.id)window.renderMaster()
  }

  function buildUI(){
    const tabs=document.querySelector('.tabs');if(!tabs||gid('shiftTab'))return;const btn=document.createElement('button');btn.className='tab';btn.dataset.tab='shift';btn.textContent='シフト自動作成';tabs.appendChild(btn);const sec=document.createElement('section');sec.id='shiftTab';sec.className='hidden';sec.innerHTML=`
      <section class="panel"><div class="head"><div><b>シフト自動作成</b><div class="small">休み希望と従業員マスタの勤務条件を守り、365日出荷予測・出勤日数・出荷人時から残りを自動配置します。</div></div><div class="toolbar"><button id="shiftRefreshBtn">再読込</button><button class="primary" id="shiftAutoBtn">自動作成</button></div></div>
      <div class="shift-controls"><div><label>対象月度</label><input id="shiftMonth" type="month"></div><div><label>対象期間</label><div id="shiftPeriod" class="readonly-box">—</div></div><div><label>使用OPLH</label><div id="shiftOplh" class="readonly-box">—</div></div><div><label>操作</label><div class="small shift-help">セルクリック：未作成/自動 → 休み固定 → 出勤固定 → 未作成</div></div></div>
      <div class="shift-kpis"><div class="kpi"><span class="lab">必要人数不足日</span><b id="shiftShortDays">—</b><div class="hint">人数または人時が不足する日</div></div><div class="kpi"><span class="lab">配置出勤日数</span><b id="shiftAssignedDays">—</b><div class="hint">全員の出勤セル合計</div></div><div class="kpi"><span class="lab">目標出勤日数</span><b id="shiftTargetDays">—</b><div class="hint">月間人時設定の合計</div></div><div class="kpi"><span class="lab">手動固定</span><b id="shiftLockedCount">—</b><div class="hint">休み希望・出勤固定</div></div><div class="kpi"><span class="lab">最大連勤</span><b id="shiftMaxStreak">—</b><div class="hint">4連勤不可の人は最大3日</div></div></div>
      <div id="shiftNotice" class="notice" style="margin-top:10px">シフトを読み込んでいます。</div><div class="shift-legend small"><span class="legend auto-work">出＝自動出勤</span><span class="legend auto-off">休＝自動休み</span><span class="legend manual-off">休★＝休み固定</span><span class="legend manual-work">出★＝出勤固定</span><span class="legend retired">退＝退職後</span><span class="legend unset">―＝未作成</span></div></section>
      <section class="panel section"><div class="head"><div><b>月度シフト表</b><div class="small">縦＝物流部全員、横＝21日～翌20日。固定セルと従業員マスタの勤務条件は自動作成しても変更されません。</div></div></div><div class="tablewrap shift-tablewrap"><table id="shiftTable" class="shift-table"><thead id="shiftHead"></thead><tbody id="shiftBody"></tbody></table></div></section>`;gid('masterTab').insertAdjacentElement('afterend',sec);gid('shiftMonth').value=gid('month')?.value||new Date().toISOString().slice(0,7);gid('shiftMonth').onchange=()=>loadShiftData(true);gid('shiftRefreshBtn').onclick=()=>loadShiftData(true);gid('shiftAutoBtn').onclick=generateSchedule;bindTabs()
  }
  function bindTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));const tab=b.dataset.tab;gid('monthlyTab').classList.toggle('hidden',tab!=='monthly');gid('masterTab').classList.toggle('hidden',tab!=='master');gid('shiftTab').classList.toggle('hidden',tab!=='shift');if(tab==='shift'){if(!state.loaded&&gid('month')?.value)gid('shiftMonth').value=gid('month').value;await loadShiftData(false)}})}
  function setNotice(t,type='warn'){const e=gid('shiftNotice');if(e){e.textContent=t;e.className='notice shift-note '+type}}
  function setBusy(on,label='処理中…'){const b=gid('shiftAutoBtn'),r=gid('shiftRefreshBtn');if(b){b.disabled=on;b.textContent=on?label:'自動作成'}if(r)r.disabled=on}
  async function ensureStaffing(planMonth,slist,dlist){let rows=await rest('logistics_monthly_staffing',`owner_id=eq.${user.id}&plan_month=eq.${planMonth}&select=*`),missing=slist.filter(s=>!(rows||[]).some(r=>r.staff_id===s.id));if(!missing.length)return rows||[];let prev=[];try{prev=await rest('logistics_monthly_staffing',`owner_id=eq.${user.id}&plan_month=lt.${planMonth}&select=*&order=plan_month.desc`)}catch{}const inserts=missing.map(s=>{const def=dlist.find(d=>d.staff_id===s.id),p=(prev||[]).find(x=>x.staff_id===s.id);return{owner_id:user.id,staff_id:s.id,plan_month:planMonth,work_days:p?num(p.work_days):num(def?.default_work_days),included:p?p.included:!!def,start_time:p?.start_time||def?.start_time||null,end_time:p?.end_time||def?.end_time||null,break_start:p?.break_start??def?.break_start??null,break_end:p?.break_end??def?.break_end??null}});if(inserts.length)await rest('logistics_monthly_staffing','',{method:'POST',body:JSON.stringify(inserts)});return await rest('logistics_monthly_staffing',`owner_id=eq.${user.id}&plan_month=eq.${planMonth}&select=*`)}
  async function loadShiftData(force=false){if(!user?.id||!gid('shiftMonth'))return;const ym=gid('shiftMonth').value||new Date().toISOString().slice(0,7);if(state.loaded&&!force&&state.month===ym){renderShift();return}setBusy(true,'読込中…');setNotice('シフト・出荷予測・月間人時・勤務条件を読み込んでいます。','warn');try{const p=periodForMonth(ym),[slist,dlist,forecasts,existing,exactPlan,prevPlan]=await Promise.all([rest('logistics_staff',`owner_id=eq.${user.id}&is_active=eq.true&select=*&order=name.asc`),rest('logistics_staff_defaults',`owner_id=eq.${user.id}&select=*`),rest('forecast365_daily',`owner_id=eq.${user.id}&forecast_date=gte.${p.start}&forecast_date=lte.${p.end}&select=forecast_date,weekday,event_type,final_forecast,required_people&order=forecast_date.asc`),rest('logistics_daily_shifts',`owner_id=eq.${user.id}&shift_date=gte.${p.start}&shift_date=lte.${p.end}&select=*`),rest('logistics_monthly_plans',`owner_id=eq.${user.id}&plan_month=eq.${p.planMonth}&select=*`),rest('logistics_monthly_plans',`owner_id=eq.${user.id}&plan_month=lt.${p.planMonth}&select=*&order=plan_month.desc&limit=1`)]),active=(slist||[]).filter(x=>!String(x.name||'').startsWith('__')&&visibleInPeriod(x,p.start)),staffing=await ensureStaffing(p.planMonth,active,dlist||[]),plan=exactPlan?.[0]||prevPlan?.[0];Object.assign(state,{month:ym,planMonth:p.planMonth,start:p.start,end:p.end,dates:p.dates,staff:active,defaults:dlist||[],staffing:staffing||[],forecast:new Map((forecasts||[]).map(x=>[x.forecast_date,x])),shifts:new Map(),targetOplh:num(plan?.target_oplh)||32,bufferPct:num(plan?.safety_buffer_pct),planSource:exactPlan?.[0]?'current':prevPlan?.[0]?'previous':'default',loaded:true});for(const row of existing||[])state.shifts.set(key(row.staff_id,row.shift_date),{...row,exists:true});renderShift();const saved=(existing||[]).length;setNotice(saved?`保存済みシフト ${saved}セルを読み込みました。固定セルと勤務条件を守って再配置できます。`:'まだシフトは作成されていません。休み希望を固定してから「自動作成」を押してください。',saved?'good':'warn')}catch(e){console.error(e);setNotice('シフトの読み込みに失敗しました: '+(e?.message||e),'bad')}finally{setBusy(false)}}
  function renderShift(){if(!state.loaded)return;gid('shiftPeriod').textContent=`${state.start.slice(5).replace('-','/')} ～ ${state.end.slice(5).replace('-','/')}`;const src=state.planSource==='current'?'当月設定':state.planSource==='previous'?'直近月設定を使用':'既定値';gid('shiftOplh').textContent=`${state.targetOplh.toFixed(2)}（${src}）`;const m=calcMetrics();gid('shiftShortDays').textContent=m.shortDays+'日';gid('shiftAssignedDays').textContent=m.assignedDays+'日';gid('shiftTargetDays').textContent=m.targetDays+'日';gid('shiftLockedCount').textContent=m.locked+'件';gid('shiftMaxStreak').textContent=m.maxStreak+'日';const head=gid('shiftHead');head.innerHTML='';const tr=document.createElement('tr');tr.innerHTML='<th class="shift-sticky shift-name-col">氏名</th><th class="shift-type-col">区分</th><th class="shift-days-col">出勤<br>実/目</th>';for(const d of state.dates){const inf=dateInfo(d),req=requiredPeople(d),ac=assignedCount(d),rh=requiredHours(d),ah=assignedHours(d),bad=ac<req||ah+.01<rh,f=state.forecast.get(d),th=document.createElement('th'),holiday=isJapaneseHoliday(d);th.className='shift-day-head '+(bad?'short':'ok');th.title=`${d} ${inf.weekday}${holiday?' 祝':''} / ${f?.event_type||'通常'} / 必要 ${req}人・${rh.toFixed(1)}h / 配置 ${ac}人・${ah.toFixed(1)}h`;th.innerHTML=`<div class="shift-date">${inf.md}</div><div class="shift-week ${inf.weekend||holiday?'weekend':''}">${holiday?'祝':inf.weekday}</div><div class="shift-need">必${req}</div><div class="shift-assign">配${ac}</div>`;tr.appendChild(th)}head.appendChild(tr);const body=gid('shiftBody');body.innerHTML='';for(const s of state.staff){const target=targetDays(s.id),actual=assignedForStaff(s.id),stf=state.staffing.find(x=>x.staff_id===s.id),r=rule(s.id),trb=document.createElement('tr');if(!stf?.included)trb.classList.add('shift-row-off');const n=document.createElement('td');n.className='shift-sticky shift-name-col';n.innerHTML=`<b>${esc(s.name)}</b><div class="small">${esc(constraintText(r))}</div>`;trb.appendChild(n);const t=document.createElement('td');t.className='shift-type-col';t.textContent=s.employment_type||'';trb.appendChild(t);const ds=document.createElement('td');ds.className='shift-days-col num '+(actual===target?'':'shift-days-warn');ds.textContent=`${actual}/${target}`;trb.appendChild(ds);for(const d of state.dates){const td=document.createElement('td'),b=document.createElement('button');td.className='shift-cell-td';b.type='button';if(afterRetirement(s.id,d)){b.className='shift-cell shift-retired';b.textContent='退';b.title=`${s.name} / ${d} / 退職日後のため対象外`;b.disabled=true}else{const c=getCell(s.id,d);b.className='shift-cell '+cellClass(c);b.textContent=cellText(c);b.title=cellTitle(c,d,s.name);b.onclick=()=>cycleCell(s.id,d)}td.appendChild(b);trb.appendChild(td)}body.appendChild(trb)}}
  function cellText(c){if(!c.exists&&c.lock_type==='auto')return'―';if(c.lock_type==='manual_off')return'休★';if(c.lock_type==='manual_work')return'出★';return c.assignment==='work'?'出':'休'}
  function cellClass(c){if(!c.exists&&c.lock_type==='auto')return'shift-unset';if(c.lock_type==='manual_off')return'shift-manual-off';if(c.lock_type==='manual_work')return'shift-manual-work';return c.assignment==='work'?'shift-work':'shift-off'}
  function cellTitle(c,d,name){const mode=c.lock_type==='manual_off'?'休み固定':c.lock_type==='manual_work'?'出勤固定':!c.exists?'未作成':'自動';return`${name} / ${d} / ${mode}。クリックで切替`}
  async function cycleCell(sid,date){if(afterRetirement(sid,date))return;const c=getCell(sid,date),before={...c};try{if(c.lock_type==='manual_work'){await rest('logistics_daily_shifts',`owner_id=eq.${user.id}&staff_id=eq.${sid}&shift_date=eq.${date}`,{method:'DELETE'});state.shifts.delete(key(sid,date));renderShift();setNotice('未作成状態に戻しました。','good');return}if(c.lock_type==='auto'){c.lock_type='manual_off';c.assignment='off'}else{c.lock_type='manual_work';c.assignment='work'}c.exists=true;c.plan_month=state.planMonth;c.updated_at=new Date().toISOString();renderShift();await saveCells([c]);setNotice('手動固定を保存しました。','good')}catch(e){Object.assign(c,before);renderShift();setNotice('固定の保存に失敗しました: '+e.message,'bad')}}
  async function saveCells(cells){if(!cells.length)return;const rows=cells.map(c=>({owner_id:user.id,staff_id:c.staff_id,plan_month:state.planMonth,shift_date:c.shift_date,assignment:c.assignment,lock_type:c.lock_type,updated_at:new Date().toISOString()}));for(let i=0;i<rows.length;i+=300)await rest('logistics_daily_shifts','on_conflict=owner_id%2Cstaff_id%2Cshift_date',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify(rows.slice(i,i+300))});for(const c of cells)c.exists=true}
  function calcMetrics(){let shortDays=0,assignedDays=0,targetTotal=0,locked=0;for(const s of state.staff){targetTotal+=targetDays(s.id);assignedDays+=assignedForStaff(s.id);for(const d of state.dates)if(getCell(s.id,d).lock_type!=='auto')locked++}for(const d of state.dates)if(assignedCount(d)<requiredPeople(d)||assignedHours(d)+.01<requiredHours(d))shortDays++;return{shortDays,assignedDays,targetDays:targetTotal,locked,maxStreak:maxConsecutive()}}
  function profileData(){return state.staff.map(s=>{const target=targetDays(s.id),manualWork=state.dates.filter(d=>getCell(s.id,d).lock_type==='manual_work').length,autoAvailable=state.dates.filter(d=>getCell(s.id,d).lock_type==='auto'&&dayAllowed(s.id,d)).length;return{s,target,manualWork,remaining:Math.max(0,target-manualWork),autoAvailable}}).filter(p=>p.target>0||p.manualWork>0)}
  function candidateStaff(date,profiles){const a=[];for(const p of profiles){if(p.remaining<=0)continue;const c=getCell(p.s.id,date);if(c.lock_type!=='auto'||c.assignment==='work'||!autoAllowed(p.s.id,date))continue;const left=state.dates.filter(d=>{const x=getCell(p.s.id,d);return x.lock_type==='auto'&&x.assignment!=='work'&&dayAllowed(p.s.id,d)}).length,urg=p.remaining/Math.max(1,left),streak=projectedStreak(p.s.id,date),weekends=weekendForStaff(p.s.id),actual=assignedForStaff(p.s.id);let score=urg*10000+p.remaining*80-actual*5-weekends*(dateInfo(date).weekend?60:0)+stableTie(p.s.id,date);if(streak>6)score-=1000000;else if(streak>=5)score-=streak*150;a.push({p,score})}return a.sort((x,y)=>y.score-x.score)}
  function chooseFillDate(p){const a=[];for(const d of state.dates){const c=getCell(p.s.id,d);if(c.lock_type!=='auto'||c.assignment==='work'||!autoAllowed(p.s.id,d))continue;const req=requiredPeople(d),assigned=assignedCount(d),gap=req-assigned,streak=projectedStreak(p.s.id,d),weekends=weekendForStaff(p.s.id),inf=dateInfo(d);let score=gap*10000+req*100-assigned*20-weekends*(inf.weekend?80:0)+stableTie(p.s.id,d);if(streak>6)score-=1000000;else if(streak>=5)score-=streak*200;a.push({d,score})}a.sort((x,y)=>y.score-x.score);return a[0]?.d||null}
  async function generateSchedule(){if(!state.loaded){await loadShiftData(true);if(!state.loaded)return}setBusy(true,'自動作成中…');setNotice('固定セルと従業員マスタの勤務条件を保持して再計算しています。','warn');try{for(const s of state.staff)for(const d of state.dates){if(afterRetirement(s.id,d))continue;const c=getCell(s.id,d);if(c.lock_type==='auto'){c.assignment='off';c.exists=true;c.plan_month=state.planMonth}}const profiles=profileData();let guard=0;while(guard++<5000){const deficits=state.dates.map(d=>({d,gap:requiredPeople(d)-assignedCount(d),hourGap:requiredHours(d)-assignedHours(d)})).filter(x=>x.gap>0||x.hourGap>.01).sort((a,b)=>(b.gap-a.gap)||(b.hourGap-a.hourGap)||requiredPeople(b.d)-requiredPeople(a.d));if(!deficits.length)break;let placed=false;for(const def of deficits){const cand=candidateStaff(def.d,profiles);if(!cand.length)continue;const pick=cand[0].p,c=getCell(pick.s.id,def.d);c.assignment='work';c.exists=true;pick.remaining--;placed=true;break}if(!placed)break}profiles.sort((a,b)=>(b.remaining-a.remaining)||((a.autoAvailable-a.target)-(b.autoAvailable-b.target)));for(const p of profiles)while(p.remaining>0){const d=chooseFillDate(p);if(!d)break;const c=getCell(p.s.id,d);c.assignment='work';c.exists=true;p.remaining--}const all=[];for(const s of state.staff)for(const d of state.dates)if(!afterRetirement(s.id,d))all.push(getCell(s.id,d));await saveCells(all);renderShift();const m=calcMetrics(),unmet=profiles.filter(p=>p.remaining>0);if(unmet.length)setNotice(`自動作成は保存しましたが、勤務条件または休み固定により ${unmet.length}名が目標出勤日数に届いていません。条件違反はさせず未達として残しています。`,'bad');else if(m.shortDays)setNotice(`自動作成・保存完了。勤務条件は守っていますが、必要人数または必要人時が不足する日が ${m.shortDays}日あります。`,'warn');else setNotice('自動作成・保存完了。勤務条件・月間出勤日数・日別必要人数・必要人時を満たしています。','good')}catch(e){console.error(e);setNotice('自動作成または保存に失敗しました: '+(e?.message||e),'bad')}finally{setBusy(false)}}

  installMasterConstraintHooks();buildUI();
})();
