const SB_URL='https://qfcgxefymdodjrprhfvu.supabase.co';
const SB_KEY='sb_publishable_KzELBvq1CkhnHL_CXN99GA_5-an2G6m';
const SESSION_KEY='logistics_monthly_oplh_session_v1';
const OWNER_FALLBACK=null;
const $=id=>document.getElementById(id);
let session=null,user=null,allStaff=[],activeStaff=[],todayRows=new Map(),shiftMap=new Map(),refreshPromise=null,selectedWorkDate=null;
const taskFields=['picking_minutes','pass_sort_minutes','sorting_minutes','hand_pack_minutes','auto_pack_minutes','stock_move_minutes'];

function saveSession(s){session=s;if(s)localStorage.setItem(SESSION_KEY,JSON.stringify(s));else localStorage.removeItem(SESSION_KEY)}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
async function refreshSession(){if(refreshPromise)return refreshPromise;if(!session?.refresh_token)return false;refreshPromise=(async()=>{try{const res=await fetch(SB_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:SB_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})});const d=await res.json().catch(()=>null);if(!res.ok||!d?.access_token)return false;saveSession(d);user=d.user||user;return true}catch{return false}finally{refreshPromise=null}})();return refreshPromise}
async function req(path,opt={}){const{skipRefresh=false,...fo}=opt,headers={apikey:SB_KEY,'Content-Type':'application/json',...(fo.headers||{})};if(session?.access_token)headers.Authorization='Bearer '+session.access_token;let res=await fetch(SB_URL+path,{...fo,headers});if(res.status===401&&!skipRefresh&&session?.refresh_token&&!path.includes('grant_type=')){if(await refreshSession())return req(path,{...fo,skipRefresh:true})}const txt=await res.text();let data=null;try{data=txt?JSON.parse(txt):null}catch{data=txt}if(!res.ok)throw new Error(data?.message||data?.error_description||data?.error||('HTTP '+res.status));return data}
async function rest(table,params='',opt={}){return req('/rest/v1/'+table+(params?'?'+params:''),opt)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function localDateISO(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return y+'-'+m+'-'+day}
function displayDate(iso){const d=new Date(iso+'T00:00:00');return d.toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'})}
function fmtMin(min){min=Math.max(0,Math.round(Number(min)||0));return Math.floor(min/60)+':'+String(min%60).padStart(2,'0')}
function parseTime(v){v=String(v??'').trim();if(!v)return 0;if(/^\d+$/.test(v)){const h=Number(v);return h<=24?h*60:NaN}const m=v.match(/^(\d{1,2}):([0-5]\d)$/);if(!m)return NaN;const h=Number(m[1]),mm=Number(m[2]);return h<=24?h*60+mm:NaN}
function cleanStaffName(name){return String(name||'').replace(/^\d{6}[\s\u00a0]+/,'').replace(/^LEGACY-S\d+[\s\u00a0]+/,'')}
function staffCode(name){const m=String(name||'').match(/^(\d{6}|LEGACY-S\d+)/);return m?m[1]:''}

async function login(){const em=$('email').value.trim(),pw=$('password').value;if(!em||!pw){$('authError').textContent='メールアドレスとパスワードを入力してください。';return}const b=$('loginBtn');b.disabled=true;$('authError').textContent='';try{const d=await req('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:em,password:pw}),skipRefresh:true});saveSession(d);user=d.user;showApp();await loadBase();await loadToday();await loadImportStatus()}catch(e){$('authError').textContent=e.message}finally{b.disabled=false}}
async function logout(){try{if(session?.access_token)await req('/auth/v1/logout',{method:'POST'})}catch{}saveSession(null);session=null;user=null;showApp()}
function showApp(){const on=!!session?.access_token;$('authView').classList.toggle('hidden',on);$('appView').classList.toggle('hidden',!on);$('logoutBtn').classList.toggle('hidden',!on);$('userLabel').textContent=user?.email||''}

async function loadBase(){allStaff=await rest('logistics_staff',`owner_id=eq.${user.id}&select=id,name,employment_type,is_active&order=name.asc`)||[];activeStaff=allStaff.filter(s=>s.is_active&&['パート','シルバー'].includes(s.employment_type));}
function updateDateNav(){const today=localDateISO(),d=selectedWorkDate||today;const next=$('nextDateBtn');if(next)next.disabled=d>=today}
async function changeWorkDate(days){const base=new Date((selectedWorkDate||localDateISO())+'T00:00:00');base.setDate(base.getDate()+days);const next=localDateISO(base),today=localDateISO();if(next>today)return;selectedWorkDate=next;await loadToday()}
async function loadToday(){const date=selectedWorkDate||localDateISO();selectedWorkDate=date;$('todayLabel').textContent=displayDate(date);updateDateNav();$('todayMessage').textContent='';const [rows,shifts]=await Promise.all([rest('logistics_work_time',`owner_id=eq.${user.id}&work_date=eq.${date}&select=*`),rest('logistics_daily_shifts',`owner_id=eq.${user.id}&shift_date=eq.${date}&select=staff_id,assignment`).catch(()=>[])]);todayRows=new Map((rows||[]).map(r=>[r.staff_id,r]));shiftMap=new Map((shifts||[]).map(r=>[r.staff_id,r.assignment]));renderToday()}
function renderToday(){const tb=$('todayBody');tb.innerHTML='';let done=0,total=0,target=0;for(const s of activeStaff){const r=todayRows.get(s.id),shift=shiftMap.get(s.id),isDone=!!r?.submitted_at||r?.source==='legacy_excel';if(shift!=='off')target++;if(isDone&&shift!=='off')done++;const vals=taskFields.map(f=>Number(r?.[f]||0));total+=vals.reduce((a,b)=>a+b,0);const tr=document.createElement('tr');if(shift==='off')tr.classList.add('offrow');tr.dataset.staff=s.id;tr.innerHTML=`<td><span class="rowname">${esc(cleanStaffName(s.name))}</span><span class="rowmeta">${esc(staffCode(s.name))}${shift?(' ・ '+(shift==='work'?'出勤予定':'休み')):''}</span></td>${taskFields.map((f,i)=>`<td><input class="time-input" data-field="${f}" inputmode="numeric" placeholder="0:00" value="${vals[i]?fmtMin(vals[i]):''}"></td>`).join('')}<td class="totalcell">${fmtMin(vals.reduce((a,b)=>a+b,0))}</td><td><span class="state ${isDone?'done':(shift==='off'?'off':'pending')}">${isDone?'入力済':(shift==='off'?'休み':'未入力')}</span></td><td><button class="save-row" data-save="${s.id}">保存</button></td>`;tb.appendChild(tr)}
tb.querySelectorAll('.time-input').forEach(inp=>{inp.onblur=()=>{const m=parseTime(inp.value);inp.classList.toggle('invalid',Number.isNaN(m));if(!Number.isNaN(m)&&inp.value.trim())inp.value=fmtMin(m);updateRowTotal(inp.closest('tr'))};inp.oninput=()=>updateRowTotal(inp.closest('tr'))});
tb.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>saveRow(b.dataset.save));
$('todayStaffCount').textContent=target+'人';$('todayDoneCount').textContent=done+'人';$('todayPendingCount').textContent=Math.max(0,target-done)+'人';$('todayHours').textContent=fmtMin(total)}
function updateRowTotal(tr){let total=0,ok=true;tr.querySelectorAll('.time-input').forEach(inp=>{const m=parseTime(inp.value);if(Number.isNaN(m)){ok=false;inp.classList.add('invalid')}else{inp.classList.remove('invalid');total+=m}});tr.querySelector('.totalcell').textContent=ok?fmtMin(total):'—'}
async function saveRow(staffId,silent=false){const tr=document.querySelector(`tr[data-staff="${staffId}"]`);if(!tr)return false;const body={owner_id:user.id,staff_id:staffId,work_date:selectedWorkDate||localDateISO(),source:'app',submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()};let invalid=false;tr.querySelectorAll('.time-input').forEach(inp=>{const m=parseTime(inp.value);if(Number.isNaN(m)){inp.classList.add('invalid');invalid=true}else body[inp.dataset.field]=m});if(invalid){if(!silent){$('todayMessage').className='message bad';$('todayMessage').textContent='赤い入力欄を修正してください。例：3:30'}return false}try{await rest('logistics_work_time','on_conflict=owner_id%2Cstaff_id%2Cwork_date',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(body)});if(!silent){$('todayMessage').className='message ok';$('todayMessage').textContent=cleanStaffName(activeStaff.find(x=>x.id===staffId)?.name)+' さんの入力を保存しました。'}return true}catch(e){if(!silent){$('todayMessage').className='message bad';$('todayMessage').textContent='保存失敗: '+e.message}return false}}
async function saveAll(){const b=$('saveAllBtn');b.disabled=true;let ok=0,ng=0;for(const tr of document.querySelectorAll('#todayBody tr')){const has=Array.from(tr.querySelectorAll('.time-input')).some(x=>x.value.trim());if(!has)continue;(await saveRow(tr.dataset.staff,true))?ok++:ng++}await loadToday();$('todayMessage').className='message '+(ng?'bad':'ok');$('todayMessage').textContent=ng?`${ok}人保存、${ng}人は入力エラーです。`:`${ok}人分を保存しました。`;b.disabled=false}

function monthRange(){const ym=$('monthPick').value||localDateISO().slice(0,7),[y,m]=ym.split('-').map(Number);if($('monthMode').value==='calendar'){const start=new Date(y,m-1,1),end=new Date(y,m,0);return[localDateISO(start),localDateISO(end)]}const end=new Date(y,m-1,20),start=new Date(y,m-2,21);return[localDateISO(start),localDateISO(end)]}
async function loadMonth(){const[start,end]=monthRange();$('monthRange').textContent=displayDate(start)+' ～ '+displayDate(end);$('monthMessage').textContent='';try{const rows=await rest('logistics_work_time',`owner_id=eq.${user.id}&work_date=gte.${start}&work_date=lte.${end}&select=*`);renderMonth(rows||[])}catch(e){$('monthMessage').className='message bad';$('monthMessage').textContent=e.message}}
function renderMonth(rows){const totals=Object.fromEntries(taskFields.map(f=>[f,0])),byStaff=new Map();for(const r of rows){if(!byStaff.has(r.staff_id))byStaff.set(r.staff_id,Object.fromEntries(taskFields.map(f=>[f,0])));const x=byStaff.get(r.staff_id);for(const f of taskFields){const v=Number(r[f]||0);x[f]+=v;totals[f]+=v}}const ids=['mPicking','mPass','mSorting','mHand','mAuto','mStock'];taskFields.forEach((f,i)=>$(ids[i]).textContent=fmtMin(totals[f]));$('mTotal').textContent=fmtMin(Object.values(totals).reduce((a,b)=>a+b,0));const tb=$('monthBody');tb.innerHTML='';const arr=Array.from(byStaff.entries()).map(([id,v])=>({staff:allStaff.find(s=>s.id===id),v})).sort((a,b)=>String(a.staff?.name||'').localeCompare(String(b.staff?.name||''),'ja',{numeric:true}));for(const x of arr){const sum=taskFields.reduce((a,f)=>a+x.v[f],0),tr=document.createElement('tr');tr.innerHTML=`<td><b>${esc(cleanStaffName(x.staff?.name||'不明'))}</b><span class="rowmeta">${esc(staffCode(x.staff?.name||''))}${x.staff&&!x.staff.is_active?' ・ 過去在籍':''}</span></td>${taskFields.map(f=>`<td>${fmtMin(x.v[f])}</td>`).join('')}<td><b>${fmtMin(sum)}</b></td>`;tb.appendChild(tr)}if(!arr.length)tb.innerHTML='<tr><td colspan="8" class="muted">この期間のデータはありません。</td></tr>'}
async function loadImportStatus(){try{
 const getCount=async(skipRefresh=false)=>{
  const headers={apikey:SB_KEY,Prefer:'count=exact'};
  if(session?.access_token)headers.Authorization='Bearer '+session.access_token;
  const res=await fetch(SB_URL+'/rest/v1/logistics_work_time?owner_id=eq.'+user.id+'&source=eq.legacy_excel&select=id&limit=1',{headers});
  if(res.status===401&&!skipRefresh&&session?.refresh_token&&await refreshSession())return getCount(true);
  if(!res.ok)throw new Error('HTTP '+res.status);
  const cr=res.headers.get('content-range')||'',parts=cr.split('/'),total=parts.length>1?parts[1]:'';
  return total&&total!=='*'?Number(total):null;
 };
 const total=await getCount();
 $('importStatus').textContent=total!=null?(total+'件の旧Excelデータを移行済みです（2026/2/21〜2026/9/19）。'):'旧Excelデータを移行済みです（2026/2/21〜2026/9/19）。';
}catch(e){$('importStatus').textContent='旧Excelデータを移行済みです（2026/2/21〜2026/9/19）。'}}

document.querySelectorAll('.tab').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));['today','monthly','admin'].forEach(t=>$(t+'Tab').classList.toggle('hidden',b.dataset.tab!==t));if(b.dataset.tab==='monthly')await loadMonth();if(b.dataset.tab==='admin')await loadImportStatus()});
$('loginBtn').onclick=login;$('logoutBtn').onclick=logout;$('reloadTodayBtn').onclick=loadToday;$('prevDateBtn').onclick=()=>changeWorkDate(-1);$('nextDateBtn').onclick=()=>changeWorkDate(1);$('saveAllBtn').onclick=saveAll;$('loadMonthBtn').onclick=loadMonth;$('monthMode').onchange=loadMonth;
selectedWorkDate=localDateISO();
$('monthPick').value=localDateISO().slice(0,7);
(async()=>{session=loadSession();if(session?.access_token){try{user=await req('/auth/v1/user');showApp();await loadBase();await loadToday();await loadImportStatus()}catch{saveSession(null);session=null;user=null;showApp()}}else showApp()})();